---
# Spring Boot application repository
repo_url: "https://github.com/koujienami/aws-study.git"

# Git branch to deploy
branch: "main"

# Application deployment directory on EC2
app_dir: /home/ec2-user/aws-study

# Spring Boot execution port
app_port: 8080

# Java package version
java_package: "java-21-amazon-corretto-devel"

# Application log file
app_log: "app.log" 