# Ansible Playbook開始
# Spring BootアプリのリポジトリをEC2へクローンする処理

- name: Clone repository

  # 対象ホストグループ
  # inventory.ini の [web] に対応
  hosts: web

  # sudo権限で実行
  become: yes

  # 実行タスク一覧
  tasks:

    # Gitリポジトリをクローンするタスク
    - name: Clone repository

      # gitモジュールを使用
      git:

        # GitHubリポジトリURL
        # vars.yml の repo_url を参照
        repo: "{{ repo_url }}"

        # EC2上の配置先ディレクトリ
        # /home/ec2-user/aws-study など
        dest: "{{ app_dir }}"

        # デプロイするブランチ指定
        # mainブランチなど
        version: "{{ branch }}"

        # 既存ディレクトリがあっても強制更新
        # git pull相当の挙動
        force: yes