- name: Clone repository
  hosts: web
  become_user: ec2-user

  tasks:
    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: /home/ec2-user/aws-study
        version: main
        force: yes 