---
- name: Install Java on EC2
  hosts: web
  become: true

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install Amazon Corretto 17
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Show Java version
      debug:
        var: java_version.stderr_lines